### ISSUE TITLE
Broken link in the Readme file

### ISSUE THREAD

**Issue by AbdelouahabMbarki** [kubesphere-sigs/ks-devops#57]
There is broken link to https://github.com/kubesphere-sigs/ks-devops/blob/master/config/samples/kubesphere.yaml in the readme file 

![image](https://user-images.githubusercontent.com/52507296/125991893-6abadb24-1468-42a5-b76d-08934d177eb7.png)

**Comment by JohnNiang** [comment]
Hi @AbdelouahabMbarki , thank you for you careful discovery. kubesphere.yaml looks like this:

```yaml
authentication:
  authenticateRateLimiterDuration: 10m0s
  authenticateRateLimiterMaxTries: "10"
  jwtSecret: Z1TBo4jUSB5Rs6eyLqHSJ77GXtG8NhSP
  loginHistoryRetentionPeriod: 168h
  maximumClockSkew: 10s
devops:
  host: http://172.18.0.2:30180/ # Need to change
  maxConnections: "100"
  password: 01UccBiGssWh4YNvAYnRrR # Need to change
  username: admin
```

And you can put it into project root.

### How to get Jenkins password

```bash
kubectl get secret --namespace kubesphere-devops-system ks-ctl-jenkins -o jsonpath="{.data.jenkins-admin-password}" | base64 --decode;echo
```

Please feel free to correct me if something wrong.
