### ISSUE TITLE
Support using tekton to create pipelines

### ISSUE THREAD

**Issue by flamywhale** [kubesphere-sigs/ks-devops#81]
Add support for using tekton to create pipelines in `ks-devops`.

/label ospp-2021

**Comment by flamywhale** [comment]
API design is [here](https://docs.google.com/document/d/1nMzb78ArsLRv6z0i-97a1ah3DPxJnjEn91ksDfGnA7Y/edit?usp=sharing).
@shihaoH @LinuxSuRen

**Comment by flamywhale** [comment]
CLI basic design can be seen [here](https://gist.github.com/flamywhale/23c557a3bbcb987c804dc53be5cfcb9b).

**Comment by flamywhale** [comment]
To simplify the usage of `Tekton` in ks-devops, I decide to create a new syntax for using devops referring to [Github Actions](https://docs.github.com/en/actions).

## TODO

What I am going to do is as follows:
1. create a new crd named **action** (pipeline crd has already been used by jenkins).
2. create the controller of the crd **action** to translate it to tekton components and run the tekton-based pipeline.

## Syntax design

Here, I will describe the example of the new devops syntax first to give you a blueprint of it.

### Overview 

* A pipeline is composed of several tasks, and each task consists of plenty of steps.
* A pipeline can specify the executing order of tasks.

```bash
┌─────────────────────────────────┐   ┌ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┐
│         Pipeline                │                          
│  ┌─────────────────────────┐    │   │name: "pipeline name"│
│  │      Task               │    │                          
│  │ ┌─────────────────────┐ │    │   │tasks:               │
│  │ │    Step             │ │    │                          
│  │ └─────────────────────┘ │──┐ │   │  - name: "task1"    │
│  │ ┌─────────────────────┐ │  │ │        steps:            
│  │ │    Step             │ │  │ │   │      - step1        │
│  │ └─────────────────────┘ │  │ │          - step2         
│  └─────────────────────────┘  │ │   │                     │
│  ┌─────────────────────────┐  │ │                          
│  │      Task               │  │ │   │                     │
│  │ ┌─────────────────────┐ │  │ │      - name: "task2"     
│  │ │    Step             │ │  │ │   │    need:            │
│  │ └─────────────────────┘ │◀─┘ │          - task1         
│  │ ┌─────────────────────┐ │    │   │    steps:           │
│  │ │    Step             │ │    │          - step1         
│  │ └─────────────────────┘ │    │   │      - step2        │
│  └─────────────────────────┘    │                          
└─────────────────────────────────┘   └ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┘                              
```

### Details of syntax

The detailed syntax can be describe by the following yaml file:
```yaml
name: "pipeline name" # required, specify the pipeline name
tasks: # tasks contains a lot of task
  - name: "task name 1" # required, specify the task name
    need: [""] # names of tasks which must be done before the current task
    uses: "template name of task" # optional, the name of template task
    with: # optional, params passed to the template task
      - name: "param key"
        value: "param value"
    env:
      - name: "environment variable name"
        value: "environment variable value"
    steps:
      - name: "step name 1" # required, the name of the step
        image: "gcr.io/image:tag" # optional, the image url of the container
        workspace: "/path/to/execute/scripts" # optional, set the workspace of the step
        command: ["echo"] # optional, entry point of the container image
        args: ["hello", "step 1"] # optional, arguments of the entry point
        script: | # optional, command line scripts
          # command line scripts
          # e.g.
          ls
          echo "hello step 1"
```

### Use cases

#### hello world
 
The following pipeline will print `hello world`.

```yaml
name: "Hello world"
tasks:
  - name: "echo-hello-world-task"
    steps:
      - name: "echo-hello-world-step"
        image: "ubuntu:16.04"
        command: ["/bin/bash"]
        args: ["-c", "echo hello world"]
```

#### Using git task template

This example is about how to use predefined task template.

```yaml
name: "Git clone"
tasks:
  - name: "git-clone-task"
    uses: "git-cli"
    with:
      - name: "GIT_URL"
        value: "https://github.com/kubesphere/ks-devops"
      - name: "GIT_REVISION"
        value: "master"
      - name: "GIT_SECRET"
        value: "${GIT_TOKEN}"
    env:
      - name: "GIT_TOKEN"
        value: "token"
```
-----

Depending on the above examples, we can briefly describe the usage of an image-based task and a template-based task.
* We can choose only one format of task to work in each task.
  * If we decide to use an image-based task, the keyword `steps` and its content are needed, just like the example `hello world`.
  * If we decide to use a template-based task, the keyword `uses` and `with` are needed. (See the example of `git clone`)
    * `uses` provides the template task name.
    * `with` provides the params needed to pass to the template.
